#redis配置
spring:
  data:
    redis:
      #redis连接地址
      host: 120.55.249.102
      password: banmu888
      #redis 端口
      port: 6379
      #redis数据库编号
      database: 0
      #连接超时时间
      timeout: 3000
      lettuce:
        pool:
          max-active: 8  #最大活跃连接数
          max-wait: -1ms #最大等待时间-1 表生无限等待
          min-idle: 0 #最小空闲连接数
          max-idle: 8 #最大空闲连接数

  datasource:
    url: jdbc:mysql:///springboot-demo?serverTimezone=GMT%2B8&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
     initial-size: 5
     min-idle: 5
     max-active: 20
     max-wait: 60000
     time-between-eviction-runs-millis: 60000
     min-evictable-idle-time-millis: 300000
     validation-query: SELECT 1 FROM DUAL
     test-while-idle: true
     test-on-borrow: true
     test-on-return: false
     web-stat-filter:
       enabled: true
     stat-view-servlet:
       enabled: true
       url-pattern: /druid/*
       login-username: admin
       login-password: admin
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: dev
        register-enabled: false
server:
  port: 8868

netty:
  chat:
    port: 8089 # Netty 服务端口（WebSocket 连接）

#是否开启token登入验证
token-check: false
#文件上传的根路径
uploadBase: /cloud_data
