spring:
  profiles:
    active: @profileActive@
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  gson:
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: bs-manage
# MyBatis-plus配置
mybatis-plus:
  # MyBatis Mapper所对应的XML文件位置
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      # 主键类型 0:数据库ID自增 1.未定义 2.用户输入 3 id_worker 4.uuid 5.id_worker字符串表示
      id-type: AUTO
      # 默认数据库表下划线命名
      table-underline: true             #不开启驼峰自动映射,遵循php版本继续使用下划线

logging:
  config: classpath:config/@profileActive@/logback-spring.xml
